CREATE TABLE contato(
    id BIGINT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    numero VARCHAR(50) NOT NULL
)ENGINE= InnoDB DEFAULT CHARSET=utf8;

INSERT INTO contato(nome,numero) VALUES ('Gabriel','40028922');